=== gitneya/Framework/Framework/src/main/resources/frameworkConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="framework-config">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="actions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="action">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="action-name" type="xs:string"/>
										<xs:element name="url-pattern" type="xs:string"/>
										<xs:element name="form-name" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="forms">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="form">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="form-class" type="xs:string"/>
										<xs:element name="form-name" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gitneya/Framework/Framework/src/test/resources/framework.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-config xsi:noNamespaceSchemaLocation="frameworkConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<actions>
		<action>
			<action-name>zzzzzzzzzzzzz</action-name>
			<url-pattern>aaaaaaaaaaaaaaa</url-pattern>
			<form-name>bbbbbbbbbbbbbbbbbb</form-name>
		</action>
		
		<action>
			<action-name>ggggg</action-name>
			<url-pattern>ddddd</url-pattern>
			<form-name>ccccc</form-name>
		</action>
		
		<action>
			<action-name>11111111111ggggg</action-name>
			<url-pattern>2222222222ddddd</url-pattern>
			<form-name>3333333333ccccc</form-name>
		</action>
		
	</actions>
	
	<forms>
		<form>
			<form-class>KOKOKOKOKOKO</form-class>
			<form-name>FIFIFIFIFIFI</form-name>
		</form>
	</forms>
	
	<actions>
	<action>
			<action-name>0000000000</action-name>
			<url-pattern>00000000000</url-pattern>
			<form-name>000000000000</form-name>
		</action>
	
	</actions>
</framework-config>

=== gitneya/Framework/TestFramework/src/main/resources/framework.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-config xsi:noNamespaceSchemaLocation="frameworkConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<actions>
		
		<action>
			<action-name>BeanAction</action-name>
			<url-pattern>bean.frmk</url-pattern>
			<form-name>FormBeanName</form-name>
		</action>
		
	</actions>
	<forms>
		<form>
			<form-class>FormBeanClass</form-class>
			<form-name>FormBeanName</form-name>
		</form>
	</forms>
</framework-config>
